# Case study: Clean Energy business
# Storefront service expecting increased traffic
# Scheduler service has no additional load
version: "3.9"

services:
  storefront:
    build: .
  database:
    image: "mysql"